import jsPDF from "jspdf";

export function generateCareerPDF(data) {
  const doc = new jsPDF();

  doc.setFontSize(20);
  doc.text("AI Career Guidance Report", 20, 20);

  doc.setFontSize(12);
  doc.text("Generated by Cerevo Career Platform", 20, 30);

  doc.line(20, 35, 190, 35);

  doc.text(`Recommended Stream: ${data.recommended_stream}`, 20, 50);
  doc.text(`Confidence Score: ${data.score}`, 20, 60);

  doc.text("Career Opportunities:", 20, 80);
  data.career_outcomes?.forEach((career, index) => {
    doc.text(`- ${career}`, 25, 90 + index * 8);
  });

  doc.text("Entrance Exams:", 20, 140);
  data.entrance_exams?.forEach((exam, index) => {
    doc.text(`- ${exam}`, 25, 150 + index * 8);
  });

  doc.text("Recommendation:", 20, 200);
  doc.text(
    "This career path matches your interests, skills and academic profile. Start preparing today!",
    20,
    210,
    { maxWidth: 170 }
  );

  doc.save("Career_Report.pdf");
}
